import React from "react";
import { Link } from "react-router-dom";
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Header from "./Header";
import Footer from "./Footer";


const PrivacyPolicy = () => {

    return (
        <>
            <Header />
            <div className="aboutUs-div">
                <div className="container-fluid">
                    <div className="about-us-container">
                        <Row>
                            <Col sm={12}>
                                <h2 className="titleAbout">Privacy</h2>
                            </Col>
                        </Row>
                        <Row >

                            <Col sm={11}>
                                <p className="privacy-content">
                                    ViRViT (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by ViRViT.

                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, ViRViT. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    <strong>Definitions and key terms</strong>
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">

                                    To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:

                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Talent-Merge Pte Ltd, (51 Goldhill Plaza #21-10 Singapore 308900) that is responsible for your information under this Privacy Policy.   </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Country: where ViRViT or the owners/founders of ViRViT are based, in this case is Singapore
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Customer: refers to the company, organization or person that signs up to use the ViRViT Service to manage the relationships with your consumers or service users.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit ViRViT and use the services.
                                </p>
                            </Col>
                        </Row>

                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Personnel: refers to those individuals who are employed by ViRViT or are under contract to perform a service on behalf of one of the parties.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                • Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                • Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                • Service: refers to the service provided by ViRViT as described in the relative terms (if available) and on this platform.
                                </p>
                            </Col>
                        </Row>


                    </div>

                </div>
            </div>
            <Footer />
        </>
    )
}


export default PrivacyPolicy;