import React from "react";
import { Link } from "react-router-dom";
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Header from "./Header";
import Footer from "./Footer";

const TermsCondition = () => {
    return (
        <>
            <Header />
            <div className="aboutUs-div">
                <div className="container-fluid">
                    <div className="about-us-container">
                        <Row>
                            <Col sm={12}>
                                <h2 className="titleAbout">Terms And Condition</h2>
                            </Col>
                        </Row>

                        <Row>
                            <Col sm={12}>
                                <p className="privacy-content">
                                    <strong>General Terms</strong>
                                </p>

                            </Col>
                        </Row>
                        <Row >

                            <Col sm={11}>
                                <p className="privacy-content">
                                    By accessing and placing an order with ViRViT, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and ViRViT.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    Under no circumstances shall ViRViT team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if ViRViT team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    ViRViT will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.
                                </p>
                            </Col>
                        </Row>

                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    <strong>License</strong>
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">

                                ViRViT grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website/app strictly in accordance with the terms of this Agreement.

                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                These Terms & Conditions are a contract between you and ViRViT (referred to in these Terms & Conditions as "ViRViT", "us", "we" or "our"), the provider of the ViRViT website and the services accessible from the ViRViT website (which are collectively referred to in these Terms & Conditions as the "ViRViT Service").</p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the ViRViT Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Customer: refers to the company, organization or person that signs up to use the ViRViT Service to manage the relationships with your consumers or service users.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit ViRViT and use the services.
                                </p>
                            </Col>
                        </Row>

                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Personnel: refers to those individuals who are employed by ViRViT or are under contract to perform a service on behalf of one of the parties.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
                                </p>
                            </Col>
                        </Row>
                        <Row>
                            <Col sm={11}>
                                <p className="privacy-content">
                                    • Service: refers to the service provided by ViRViT as described in the relative terms (if available) and on this platform.
                                </p>
                            </Col>
                        </Row>


                    </div>

                </div>
            </div>
            <Footer />
        </>
    )
}

export default TermsCondition;